### ISSUE TITLE
Running pubsub_unsubscribe with no arguments seems to stop everything

### ISSUE THREAD

**Issue by jammed343** [thefab/tornadis#17]
In on_close method

```
@tornado.gen.coroutine
def on_close(self):
     if self.client.subscribed:
         print (yield self.client.pubsub_unsubscribe())
         print 'test'
```

Will not print 'test' for me. Everything after `pubsub_unsubscribe` with no arguments doesn't seem to run, though it should unsubscribe all channels.
But if I use pubsub_unsubscribe with a channel it seems to work.

**Comment by jammed343** [comment]
Using a `yield self.client.pubsub_punsubscribe('sample:*')` seems to be a workaround, if you use a prefix for everything, but according to redis docs running unsubscribe should unsubscribe from everything

**Comment by thefab** [comment]
you are right => let's fix it

**Comment by thefab** [comment]
I suppose you can use yield self.client.pubsub_punsubscribe('*') as a real workaround

**Comment by thefab** [comment]
thanks

**Comment by jammed343** [comment]
Thanks for fixing this, it's more straightforward error now, curious to know why this is an error instead of unsubscribing all like the redis docs.

**Comment by thefab** [comment]
I don't understand your comment.

see b171af91a78137c650fa426ed545a7b3347a1cc2 new test

you can use pubsub_punsubscribe and pubsub_unsubscribe without args (as redis docs said)

but

pubsub_psubscribe and pubsub_subscribe will raise a ClientException if there is no args (as redis docs)

**Comment by thefab** [comment]
just merged this in tornado42 branch (BTW)

**Comment by jammed343** [comment]
Oh it was just a misunderstanding. I now see you fixed those other errors as well.
