### ISSUE TITLE
Document or deal with hiredis.ReplyError

### ISSUE THREAD

**Issue by thefab** [thefab/tornadis#18]
import tornado
import tornadis
import logging
logging.basicConfig(level=logging.CRITICAL)

@tornado.gen.coroutine
def talk_to_redis():
    result = yield client.call("PNG")
    print type(result)
    print "Result: %s" % result

loop = tornado.ioloop.IOLoop.instance()
client = tornadis.Client()
loop.run_sync(talk_to_redis)

**Comment by jammed343** [comment]
True I have ran into this, I am simply checing if the type of result is a `hiredis.ReplyError` but really `hiredis.ReplyError` should be raised.

**Comment by thefab** [comment]
done in tornado42 branch and in master

examples updated
