### ISSUE TITLE
Password option support

### ISSUE THREAD

**Issue by jammed343** [thefab/tornadis#20]
Like `tornado-redis` and `redis-py` support is needed for a password keyword argument when connecting to the client. 

eg. https://github.com/andymccurdy/redis-py/blob/81429b44acff3f238a212a1651241b49cde76c85/redis/connection.py#L387

**Comment by jammed343** [comment]
I have manually monkey patched this for myself to confirm that in can work with a simple call for

AUTH PASSWORD

Keep in mind this must be added to Client so that it can enabled for PubsubClient too (which doesn't allow a manual `call` on itself, so currently there is no way to have AUTH on a pubsub client without changing the code)

I will try and change the official project too if it's not already done before my changes

**Comment by thefab** [comment]
thanks ! I will review this soon. Looks promising !

**Comment by thefab** [comment]
ok many thanks for this, I'm going to add a test

**Comment by thefab** [comment]
see comment on #21

**Comment by thefab** [comment]
thanks @masom for pointing this

**Comment by thefab** [comment]
@masom: just found some nasty problems with incorrect passwords but nothing to reproduce your problem ! I just pushed a new test in test_pools.py like your use case but it pass :-/ Can you provide some details ?

**Comment by masom** [comment]
@thefab I'm using the pypi version of the package. I'll try with `master` and see if it solves the issue since there's a bunch of commits that might affect this.

**Comment by masom** [comment]
@thefab The password issue is due to using the published pypi package. Would it be possible to release a new version?

**Comment by thefab** [comment]
@masom probably next week
