### ISSUE TITLE
Best way of dealing with connection timeout issues

### ISSUE THREAD

**Issue by vgoklani** [thefab/tornadis#24]
Sorry I've been out of touch for a while. I wanted to check-in and see if there were any updates on handling connection timeouts. My previous approach was as follows:

```
import tornadis
from tornadis.exceptions import ConnectionError

results = yield client4.call("HGETALL", redis_key)
if isinstance(results, ConnectionError):
    yield client4.connect()
    results = yield client4.call("HGETALL", redis_key)
```

Is there a more optimal solution, or should I continue with this approach?

**Comment by vgoklani** [comment]
Still getting these errors when I connect to my redis server locally:

```
  [E 150918 14:13:10 ioloop:588] Exception in callback None
      Traceback (most recent call last):
        File "/opt/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 840, in start
          handler_func(fd_obj, events)
        File "/opt/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
          return fn(*args, **kwargs)
        File "/opt/anaconda/lib/python2.7/site-packages/tornadis/connection.py", line 200, in _handle_events
          self._handle_read()
        File "/opt/anaconda/lib/python2.7/site-packages/tornadis/connection.py", line 212, in _handle_read
          chunk = self._read(self.read_page_size)
        File "/opt/anaconda/lib/python2.7/site-packages/tornadis/connection.py", line 255, in _read
          raise ConnectionError("error during socket.recv: %s" % e)
      ConnectionError: error during socket.recv: [Errno 60] Operation timed out
```

**Comment by thefab** [comment]
I'm working on a doc update. I will include this.

But to reply here:
- you don't run master (in latest commits, there is no exception raising any more)
- if you run master or latest release, Client object is in auto(re)connecting mode by default so you don't have to reconnect manually

Full example:
https://github.com/thefab/tornadis/blob/master/examples/coroutines.py

Note that reconnection is automatic (without exception at all) but "exception returning" command is (of course) not sent another time (you have to do this manually if it's relevant to you).
