### ISSUE TITLE
Cluster support?

### ISSUE THREAD

**Issue by hunt3r** [thefab/tornadis#30]
Is it possible to use this client with a redis cluster connection? E.g. https://github.com/Grokzen/redis-py-cluster

Nice work by the way, works as advertised so far.

**Comment by thefab** [comment]
no there is no cluster support for the moment
and it's not possible to mix some "sync" client library (like the one you point) with tornadis 

but it should be possible to build a specific Client object supporting redis cluster, by extending tornadis Client object (it would be a nice project)

**Comment by thefab** [comment]
just updated the README, i'm closing this
