### ISSUE TITLE
how to run in production?

### ISSUE THREAD

**Issue by vgoklani** [thefab/tornadis#4]
I run multiple tornado workers for production, curious, what's the best way of sharing the connection pool? Should each worker open it's own redis connection?

**Comment by thefab** [comment]
You can use a single Client object by tornado worker (global var for example) or you can use a  ClientPool object by tornado worker (useful only if you execute blocking commands). 

But no way to share these objects between different tornado workers. And probably not useful.

**Comment by y-x-c** [comment]
Hi, I would like to ask you a few questions. My server now serves for around 300 concurrent requests (timeout after 3 seconds), and I noticed that the server get query results (from a remote Redis server, ping ~ 0.5ms ) under high latency (long queue waiting for response). I have tried following ways to decrease the latency: 
1. create several Client instance, and choose a random client to send command for each query.
2. limit the write buffer size
after experiments, it seems like that both ways do not work, so I get really confused now : (
Could you pls give me some suggestions or point out if I am using this library in a wrong way? Thank u!
