### ISSUE TITLE
tornadis can't connect in tests

### ISSUE THREAD

**Issue by xrmx** [thefab/tornadis#40]
If i run this:
```
import tornadis
from tornado.testing import AsyncTestCase, gen_test

class Test(AsyncTestCase):
    @gen_test
    def test_tornadis(self):
        client = tornadis.Client()
        yield client.call(["GET", "ciao"])
```
with `tornado.testing mytest` Tornado gives a `tornado.ioloop.TimeoutError: Operation timed out after 5 seconds`. But redis is up and running and redis-cli connects perfectly fine.

**Comment by thefab** [comment]
you have to add this method in your Test class:

```python
def get_new_ioloop(self):
    return tornado.ioloop.IOLoop.instance()
```

Without this method, you have two distinct mainloops (one for tests and one for tornadis), so it doesn't work

**Comment by xrmx** [comment]
Thanks for the answer, do you see any place where i could add it to the documentation?
