### ISSUE TITLE
Remove ioloop from PeriodicCallback

### ISSUE THREAD

**Issue by siddharthgawas-zz** [thefab/tornadis#44]
File name:  connection.py
Line number: 86
cb = tornado.ioloop.PeriodicCallback(self._on_every_second, 1000,ioloop)

**Comment by nizamsp** [comment]
May I know the reason for this fix. We are facing some blocking behavior in tornadis library. Will this fix it?

**Comment by thefab** [comment]
fixed, sorry for delay
