### ISSUE TITLE
How to set expiry time for keys?

### ISSUE THREAD

**Issue by ajayuranakar** [thefab/tornadis#48]
I am using the tornadis.Pipline() to set the data into redis is there a way that I can set an expiry time for the keys?The code is given below:
pipeline = tornadis.Pipeline()
pipeline.stack_call("SET", "key", "value")

**Comment by thefab** [comment]
```
pipeline.stack_call("SET", "key", "value", "EX", "10") ?
```

**Comment by ajayuranakar** [comment]
Thank you.

**Comment by ajayuranakar** [comment]
When I try pipeline.stack_call("SET", "SOME_KEY","SOME_VALUE, "EX", "100") I am getting the error:
 ClientError("ERR wrong number of arguments for 'set' command",), ClientError("ERR wrong number of arguments for 'set' command",)

**Comment by ajayuranakar** [comment]
I think this happens for only for Windows and it is working good for Linux.
