### ISSUE TITLE
Connection already opened

### ISSUE THREAD

**Issue by vgoklani** [thefab/tornadis#6]
Hi,

Thanks for creating this library. I followed your example for using this as an HTTP request handler here: http://tornadis.readthedocs.org/en/latest/. The first GET request works without any issues, but each subsequent request leads to this error: "you are already connected"

What's the preferred way of opening a connection in a web-server?

**Comment by thefab** [comment]
can you provide your code ?

I can't reproduce this with the given example:

``` python
import tornado
from tornado.web import RequestHandler, Application, url
import tornadis

class GetHandler(RequestHandler):

    @tornado.gen.coroutine
    def get(self):
        client = tornadis.Client(port=6379)
        yield client.connect()
        yield client.call("BLPOP", "empty", 3)
        self.finish()


app = Application([url(r"/", GetHandler)])
app.listen(8888)
tornado.ioloop.IOLoop.current().start()
```

**Comment by thefab** [comment]
something new here ?

**Comment by vgoklani** [comment]
no, this was solved in the other ticket - thanks!
